stages:
  - build
  - test
  - deploy

variables:
  # Налаштовуємо базу в пам'яті, щоб не піднімати MySQL
  APP_ENV: testing
  DB_CONNECTION: sqlite
  DB_DATABASE: ":memory:"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .phpstan.cache/

app_test:
  stage: test
  image: php:8.2
  before_script:

    # Clear PHPUnit cache
    - rm -rf .phpunit.cache

    # 1. Оновлюємо систему (якщо треба розширення)
    - apt-get update && apt-get install -y git zip unzip  libzip-dev

    # Встановлюємо PHP розширення, необхідні для Laravel (pdo_mysql, zip)
    - docker-php-ext-install pdo_mysql zip

    # Встановлюємо Composer (офіційний спосіб для Docker-образів)
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    # 2. ВСТАНОВЛЮЄМО ЗАЛЕЖНОСТІ (це створить файл autoload.php)
    - composer install --no-interaction --prefer-dist --optimize-autoloader

    # Clear Laravel cached files
    - php artisan optimize:clear

    # Run database migrations
    - php artisan migrate --force

    # Seed database
    - php artisan db:seed

    # 3. Налаштовуємо оточення
    - cp .env.example .env
    - php artisan key:generate

  script:
    - php artisan test
