stages:
  - build
  - test
  - deploy

variables:
  APP_ENV: testing
  DB_CONNECTION: sqlite
  DB_DATABASE: ":memory:"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - storage/framework/cache/

app_test:
  stage: test
  image: php:8.2

  before_script:
    # Clear PHPUnit cache
    - rm -rf .phpunit.cache

    # Update system packages and install build dependencies
    - apt-get update && apt-get install -y git zip unzip  libzip-dev

    # Install PHP extensions required for Laravel (pdo_mysql, zip)
    - docker-php-ext-install pdo_mysql zip

    # Install Composer binary via the official installer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    # Install PHP dependencies via Composer
    - composer install --no-interaction --prefer-dist --optimize-autoloader

    # Clear Laravel cached files
    - php artisan optimize:clear

    # Run database migrations
    - php artisan migrate --force

    # 3. Settings env
    - cp $TEST_ENV_FILE .env
    - php artisan key:generate

  script:
    - php artisan test
